### ISSUE TITLE
Sidebar does not render for devices with screen width less than 768 px

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-docs#2960]
Sidebar seems to be missing for devices with width less than 768px. 
This is for 768 width:
![image](https://user-images.githubusercontent.com/6242296/87411295-83c8df00-c595-11ea-9438-026ae3ff3be3.png)

This is for 767:
![image](https://user-images.githubusercontent.com/6242296/87411361-9fcc8080-c595-11ea-963d-a92fc412c5d9.png)

Ideally, I expect an hamburger icon for devices with smaller width.

**Comment by salonigoyal2309** [comment]
@ankitm123 @MarckK hey can I work on this issue during hacktoberfest 2020 ? 😄

**Comment by ankitm123** [comment]
@salonigoyal2309 Awesome, please assign it to urself.

**Comment by salonigoyal2309** [comment]
@ankitm123 I guess I don't have right permissions to assign this issue to myself.  Can you assign it to me? 😃

**Comment by ankitm123** [comment]
Try typing `/assign` it should work.

**Comment by ankitm123** [comment]
@salonigoyal2309 Any updates?

**Comment by amino19** [comment]
@ankitm123 : What's the status about this?

**Comment by ankitm123** [comment]
@amino19 the issue still exists.

**Comment by amino19** [comment]
> @amino19 the issue still exists.

I hadn't fixed the sidebar, the issue was regarding [mobile view](https://github.com/jenkins-x/jx-docs/issues/3313), and I fixed it [here](https://github.com/jenkins-x/jx-docs/pull/3381).
Pl have a view, & check whether anything from my end has pending to work-on! :slightly_smiling_face:

**Comment by ankitm123** [comment]
So, the original issue was missing sidebar for screen width less than 768px, that issue still persists, try to render this page using developer tools for any device with width less than 768px, and the sidebar is still missing: https://jenkins-x.io/v3/about/

Ofc, we dont want a sidebar, instead a hamburger icon is the right thing to do ... 

> the issue was regarding mobile view, and I fixed it here.

As for mobile view, it still seems broken for anything less than 768px, but that's completely different issue ...

**Comment by ankitm123** [comment]
FYI, If you are fixing it, let me know, and I can add an hacktoberfest label to it.

**Comment by shivam-Purohit** [comment]
@ankitm123 Is the issue still persistent? Can I work on this issue ?
